language: python            
jobs:
  include:
    - name: "Python nightly on Ubuntu Focal 20.04 Linux amd64"
      arch: amd64
      os: linux
      dist: focal
      python: nightly 
    - name: "Python 3.9.2 on macOS"
      os: osx
      osx_image: xcode11.2  
      language: shell       
    - name: "Python 3.9.2 on Windows"
      os: windows           
      language: shell       
      before_install:
        - choco install python --version 3.9.2
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
install: pip3 install --upgrade pip  
script:
 - python test.py
after_script:
  - bash ./telegram_notification.sh
  - bash ./vk_notification.sh
notifications:
  email:
    - apalikhin@mail.ru
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: test.py
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
