# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '45 * * * *'  # every day at midnight

jobs:
  build:

    runs-on:  ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        include:
          - arch: aarch64
            distro: stretch
          - arch: aarch64
            distro: buster
          - arch: aarch64
            distro: bullseye
          - arch: aarch64
            distro: ubuntu16.04
          - arch: aarch64
            distro: ubuntu18.04
          - arch: aarch64
            distro: ubuntu20.04,
          - arch: aarch64
            distro: fedora_latest
          - arch: aarch64
            distro: alpine_latest
          - arch: aarch64
            distro: archarm_latest
            
            
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Test python
      run: |
        python test.py
        
    - name: Result
      if: ${{ always() }}
      env:
          VK_PEER_ID: ${{ secrets.VK_PEER_ID }}
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          event_name: ${{ github.event_name }}
          runner_os: ${{ matrix.arch }}
          repository_git: ${{ matrix.python-version }}
          job_status: ${{ job.status }}
      run: |
        sh vk_notification.sh "$VK_PEER_ID" "$VK_TOKEN" "$event_name" "$runner_os" "$repository_git" "$job_status"
        sh telegram_notification.sh "$TELEGRAM_CHAT_ID" "$TELEGRAM_TOKEN" "$event_name" "$runner_os" "$repository_git" "$job_status"
